### ISSUE TITLE
Resize image size

### ISSUE THREAD

**Issue by lovebdsobuj** [baivong/Bangladesh-Flag-Cover#1]
First I want to say, thanks a lot for making this repo.

I have one question,
If I want to resize generate canvas image height width, then what can I do?

**Comment by lelinhtinh** [comment]
https://github.com/baivong/Bangladesh-Flag-Cover/blob/master/script.js#L77
https://github.com/baivong/Bangladesh-Flag-Cover/blob/master/style.css#L33
Replace 320 with the number of width you want, the height will automatically change accordingly.

**Comment by lovebdsobuj** [comment]
Great! It's work!

Thanks a lot once again.

![screenshot_00008_17h46m54s](https://cloud.githubusercontent.com/assets/10352682/11270033/b4658064-8ee5-11e5-9943-b6596573bf06.png)
